const SB_URL='https://lshtmesomujktcqnyzmn.supabase.co',KEY='sb_publishable_7jNPPZwZkEIpxm4QWI8qLw_tpGABo5v',SLUG='hokkaido-family-trip-2026';
const db=supabase.createClient(SB_URL,KEY),root=document.querySelector('#admin');
let DATA,tab='schedule',dayId,message='';
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

db.auth.onAuthStateChange(()=>boot());
async function boot(){
  const{data:{session}}=await db.auth.getSession();if(!session)return login();
  const{data:allowed}=await db.from('admin_allowlist').select('email').maybeSingle();if(!allowed)return denied(session.user.email);
  const{data:trip}=await db.from('trips').select('id,title').eq('slug',SLUG).single();
  const [ds,ps,is,rs,ns,es]=await Promise.all([
    db.from('trip_days').select('*').eq('trip_id',trip.id).order('day_number'),db.from('places').select('*').eq('trip_id',trip.id),
    db.from('itinerary_items').select('*').order('sort_order'),db.from('reservations').select('*').eq('trip_id',trip.id),
    db.from('trip_notes').select('*').eq('trip_id',trip.id).order('created_at',{ascending:false}),db.from('expenses').select('*').eq('trip_id',trip.id).order('spent_on',{ascending:false})]);
  const days=ds.data||[],ids=new Set(days.map(x=>x.id));DATA={session,trip,days,places:ps.data||[],items:(is.data||[]).filter(x=>ids.has(x.day_id)),reservations:rs.data||[],notes:ns.data||[],expenses:es.data||[]};
  dayId=dayId&&ids.has(dayId)?dayId:days[0]?.id;render();
}
function login(){root.className='login';root.innerHTML=`<section><a class="brand" href="index.html">HOKKAIDO 2026</a><h1>여행 관리자</h1><p>일정과 예약, 여행 메모와 비용을 안전하게 관리해요.</p><form id="login"><label>관리자 이메일<input name="email" type="email" value="amy9876@naver.com" required></label><button>이메일로 로그인 링크 받기</button></form><div id="msg"></div><small>등록된 관리자 이메일만 수정할 수 있습니다.</small></section>`;document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const email=new FormData(e.target).get('email'),m=document.querySelector('#msg');m.className='message';m.textContent='로그인 링크를 보내고 있어요…';const{error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:location.href.split('#')[0]}});m.textContent=error?'전송하지 못했어요: '+error.message:'이메일로 보낸 로그인 링크를 눌러주세요.'}}
function denied(email){root.className='login';root.innerHTML=`<section><h1>접근 권한이 없습니다</h1><p>${esc(email)}은 관리자로 등록되지 않았어요.</p><button id="out">다른 계정으로 로그인</button></section>`;document.querySelector('#out').onclick=()=>db.auth.signOut()}
function render(){root.className='workspace';root.innerHTML=`<aside class="side"><a class="brand" href="index.html">HOKKAIDO 2026</a><p>관리 중인 여행</p><strong>${esc(DATA.trip.title)}</strong><nav>${[['schedule','일정 관리'],['reservations','예약 정보'],['notes','방문 기록'],['expenses','여행 비용']].map(x=>`<button data-tab="${x[0]}" class="${tab===x[0]?'active':''}">${x[1]}</button>`).join('')}</nav><footer><small>${esc(DATA.session.user.email)}</small><button id="out">로그아웃</button></footer></aside><section class="content"><header><h1>${{schedule:'일정 관리',reservations:'예약 확인',notes:'방문 기록',expenses:'여행비 통계'}[tab]}</h1><a href="index.html" target="_blank">가족 화면 보기 ↗</a></header>${message?`<div class="message">${esc(message)}</div>`:''}<div id="panel">${panel()}</div></section>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;message='';render()});document.querySelector('#out').onclick=()=>db.auth.signOut();bind()}
function panel(){return tab==='schedule'?schedule():tab==='reservations'?reservations():tab==='notes'?notes():expenses()}
const placeFor=i=>DATA.places.find(p=>p.id===i.place_id)||{};
function routeUrl(items){const p=items.map(placeFor).filter(x=>x.name||x.address);if(!p.length)return'';if(p.length===1)return p[0].map_url||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p[0].address||p[0].name)}`;const q=x=>encodeURIComponent(x.address||x.name),parts=[`origin=${q(p[0])}`,`destination=${q(p.at(-1))}`];if(p.length>2)parts.push(`waypoints=${p.slice(1,-1).map(x=>encodeURIComponent(x.address||x.name)).join('%7C')}`);return`https://www.google.com/maps/dir/?api=1&${parts.join('&')}&travelmode=driving`}
function timing(i={}){return`<div class="timing-fields"><label>시작 시간<input name="start_time" type="time" value="${(i.start_time||'').slice(0,5)}"></label><label>이동 시간(분)<input name="travel_minutes" type="number" min="0" value="${i.travel_minutes??''}" placeholder="예: 40"></label><label>머무는 시간(분)<input name="stay_minutes" type="number" min="0" value="${i.stay_minutes??''}" placeholder="예: 60"></label></div>`}
function placeFields(p={}){return`<div class="place-fields"><label>장소 이름<input name="place_name" value="${esc(p.name||'')}" placeholder="예: 오도리공원"></label><label>Google 지도 링크<input name="map_url" type="url" value="${esc(p.map_url||'')}" placeholder="https://maps.google.com/…"></label><label>사진 링크<input name="image_url" type="url" value="${esc(p.image_url||'')}" placeholder="출처가 명확한 이미지 URL"></label></div>`}
function basics(i={}){return`<div class="main-fields"><label>일정 이름<input name="title" value="${esc(i.title||'')}" required placeholder="가족 화면에 보일 이름"></label><label>이동 방법<select name="transport_mode">${[['car','자동차'],['walk','도보'],['train','기차'],['plane','비행기']].map(x=>`<option value="${x[0]}" ${i.transport_mode===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select></label><label>상태<select name="status">${[['planned','예정'],['confirmed','확정'],['completed','완료'],['skipped','건너뜀']].map(x=>`<option value="${x[0]}" ${i.status===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select></label></div>`}
function schedule(){const items=DATA.items.filter(x=>x.day_id===dayId).sort((a,b)=>a.sort_order-b.sort_order),route=routeUrl(items);return`<div class="tabs">${DATA.days.map(d=>`<button data-day="${d.id}" class="${d.id===dayId?'active':''}">DAY ${d.day_number} · ${d.trip_date.slice(5).replace('-','.')}</button>`).join('')}</div><div class="schedule-toolbar"><div><strong>${items.length}개의 일정</strong><span>시작·이동·체류 시간을 가족 화면과 함께 관리해요.</span></div>${route?`<a class="route-link" href="${esc(route)}" target="_blank">오늘 전체 경로 지도에서 보기 ↗</a>`:''}</div><details class="new-item"><summary>＋ 새 일정 추가</summary><form id="new-schedule" class="schedule-form"><h2>새 여행지와 일정</h2>${timing()}${basics()}<label>가족에게 보이는 설명<textarea name="description" rows="3"></textarea></label>${placeFields()}<button class="save">일정 추가하기</button></form></details><div class="panel schedule-list">${items.length?items.map(card).join(''):'<div class="empty">아직 일정이 없어요. 새 일정을 추가해 주세요.</div>'}</div>`}
function card(i){const p=placeFor(i);return`<article class="schedule-card"><div class="schedule-card-head"><b>${i.sort_order}</b><div><h2>${esc(i.title)}</h2><p>${esc(p.name||'장소 정보 미등록')}</p></div>${p.image_url?`<img src="${esc(p.image_url)}" alt="" loading="lazy">`:''}</div><form class="schedule-form" data-edit="${i.id}" data-place="${i.place_id||''}">${timing(i)}${basics(i)}<label>가족에게 보이는 설명<textarea name="description" rows="3">${esc(i.description||'')}</textarea></label>${placeFields(p)}<div class="form-actions"><button class="save">변경 저장</button>${p.map_url?`<a href="${esc(p.map_url)}" target="_blank">Google 지도 열기 ↗</a>`:''}<button type="button" class="delete" data-delete="${i.id}">일정 삭제</button></div></form></article>`}
function reservations(){const done=DATA.reservations.filter(x=>['booked','paid'].includes(x.status)).length;return`<div class="panel"><div class="cards"><article><span>전체 예약</span><strong>${DATA.reservations.length}</strong></article><article><span>완료</span><strong>${done}</strong></article><article><span>확인 필요</span><strong>${DATA.reservations.length-done}</strong></article></div>${DATA.reservations.map(x=>`<article class="reservation"><div><small>${esc(x.provider||'예약처 미정')}</small><h3>${esc(x.title)}</h3><p>${esc(x.public_note||'')}</p></div><div><select data-reservation="${x.id}">${[['needed','예약 필요'],['considering','확인 중'],['booked','예약 완료'],['paid','결제 완료'],['cancelled','취소']].map(o=>`<option value="${o[0]}" ${x.status===o[0]?'selected':''}>${o[1]}</option>`).join('')}</select>${x.booking_url?`<a href="${esc(x.booking_url)}" target="_blank">예약 페이지 ↗</a>`:''}</div></article>`).join('')}</div>`}
function notes(){return`<div class="panel grid"><form id="note" class="form"><h2>새 여행 메모</h2><label>관련 일정<select name="itinerary_item_id"><option value="">여행 전체</option>${DATA.items.map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join('')}</select></label><div class="row"><label>종류<select name="note_type"><option value="memory">방문 후기</option><option value="tip">다음 여행 팁</option><option value="change">변경 사항</option></select></label><label>평점<select name="rating"><option value="">없음</option>${[5,4,3,2,1].map(n=>`<option>${n}</option>`).join('')}</select></label></div><label>메모<textarea name="content" rows="7" required></textarea></label><button>메모 저장</button></form><div class="records"><h2>저장된 기록</h2>${DATA.notes.length?DATA.notes.map(x=>`<article class="record"><small>${esc(x.note_type)} ${x.rating?'· '+'★'.repeat(x.rating):''}</small><p>${esc(x.content)}</p><time>${new Date(x.created_at).toLocaleDateString('ko-KR')}</time></article>`).join(''):'<p>아직 기록이 없어요.</p>'}</div></div>`}
const cats={flight:'항공',hotel:'숙박',transport:'교통',food:'식비',shopping:'쇼핑',ticket:'입장료',insurance:'보험',etc:'기타'};
function expenses(){const total=DATA.expenses.reduce((s,x)=>s+Number(x.amount_krw||0),0),groups=Object.entries(cats).map(([k,v])=>[k,v,DATA.expenses.filter(x=>x.category===k).reduce((s,x)=>s+Number(x.amount_krw||0),0)]).filter(x=>x[2]);return`<div class="panel"><div class="expense-total"><span>현재 기록된 총 여행비</span><strong>${total.toLocaleString()}원</strong><p>항공·숙박·보험을 포함한 현재 금액입니다.</p></div><div class="grid" style="margin-top:15px"><form id="expense" class="form"><h2>비용 추가</h2><div class="row"><label>사용일<input type="date" name="spent_on" value="2026-08-28" required></label><label>분류<select name="category">${Object.entries(cats).map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select></label></div><label>내용<input name="description" required></label><label>금액(원)<input name="amount" type="number" min="0" required></label><button>비용 저장</button></form><div class="costs"><h2>항목별 통계</h2>${groups.map(x=>`<div><span>${x[1]}</span><i><b style="width:${Math.max(5,x[2]/total*100)}%"></b></i><strong>${x[2].toLocaleString()}원</strong></div>`).join('')}</div></div><div class="expense-list">${DATA.expenses.map(x=>`<div><time>${x.spent_on}</time><span>${esc(x.description)}</span><b>${Number(x.amount_krw).toLocaleString()}원</b></div>`).join('')}</div></div>`}
function formValues(f){const v=Object.fromEntries(new FormData(f)),place={name:v.place_name.trim(),map_url:v.map_url.trim()||null,image_url:v.image_url.trim()||null};delete v.place_name;delete v.map_url;delete v.image_url;v.start_time=v.start_time||null;v.travel_minutes=v.travel_minutes===''?null:Number(v.travel_minutes);v.stay_minutes=v.stay_minutes===''?null:Number(v.stay_minutes);return{v,place}}
async function savePlace(id,p){if(id){const{error}=await db.from('places').update(p).eq('id',id);if(error)throw error;return id}if(!p.name)return null;const{data,error}=await db.from('places').insert({...p,trip_id:DATA.trip.id}).select('id').single();if(error)throw error;return data.id}
function bind(){
  document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{dayId=b.dataset.day;render()});
  const add=document.querySelector('#new-schedule');if(add)add.onsubmit=async e=>{e.preventDefault();try{const{v,place}=formValues(add),place_id=await savePlace(null,place),sort_order=Math.max(0,...DATA.items.filter(x=>x.day_id===dayId).map(x=>x.sort_order))+1,{error}=await db.from('itinerary_items').insert({...v,day_id:dayId,place_id,sort_order,is_published:true});if(error)throw error;message='새 일정을 추가했어요. 가족 화면에도 바로 반영됩니다.'}catch(e){message='일정을 추가하지 못했어요: '+e.message}await boot()};
  document.querySelectorAll('[data-edit]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();try{const{v,place}=formValues(f),place_id=await savePlace(f.dataset.place||null,place),{error}=await db.from('itinerary_items').update({...v,place_id}).eq('id',f.dataset.edit);if(error)throw error;message='일정을 저장했어요. 가족 화면에도 같은 내용이 보입니다.'}catch(e){message='저장하지 못했어요: '+e.message}await boot()});
  document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{const i=DATA.items.find(x=>x.id===b.dataset.delete);if(!confirm(`‘${i?.title||'이 일정'}’을 삭제할까요? 삭제한 일정은 되돌릴 수 없어요.`))return;const{error}=await db.from('itinerary_items').delete().eq('id',b.dataset.delete);message=error?'삭제하지 못했어요: '+error.message:'일정을 삭제했어요.';await boot()});
  document.querySelectorAll('[data-reservation]').forEach(s=>s.onchange=async()=>{await db.from('reservations').update({status:s.value,updated_at:new Date().toISOString()}).eq('id',s.dataset.reservation);message='예약 상태를 저장했어요.';await boot()});
  const n=document.querySelector('#note');if(n)n.onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(n));v.trip_id=DATA.trip.id;v.itinerary_item_id=v.itinerary_item_id||null;v.rating=Number(v.rating)||null;await db.from('trip_notes').insert(v);message='메모를 저장했어요.';await boot()};
  const x=document.querySelector('#expense');if(x)x.onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(x));v.trip_id=DATA.trip.id;v.amount=Number(v.amount);v.amount_krw=v.amount;v.currency='KRW';await db.from('expenses').insert(v);message='비용을 저장했어요.';await boot()}
}
boot();
