const SB_URL='https://lshtmesomujktcqnyzmn.supabase.co',KEY='sb_publishable_7jNPPZwZkEIpxm4QWI8qLw_tpGABo5v',SLUG='hokkaido-family-trip-2026';
const db=supabase.createClient(SB_URL,KEY),root=document.querySelector('#admin');
let DATA,tab='schedule',dayId,message='';
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

db.auth.onAuthStateChange(()=>boot());
async function boot(){
  const{data:{session}}=await db.auth.getSession();if(!session)return login();
  const{data:allowed}=await db.from('admin_allowlist').select('email').maybeSingle();if(!allowed)return denied(session.user.email);
  const{data:trip}=await db.from('trips').select('id,title').eq('slug',SLUG).single();
  const [ds,ps,is,rs,fs,ns,es,ts,pos,pps,rps]=await Promise.all([
    db.from('trip_days').select('*').eq('trip_id',trip.id).order('day_number'),db.from('places').select('*').eq('trip_id',trip.id),
    db.from('itinerary_items').select('*').order('sort_order'),db.from('reservations').select('*').eq('trip_id',trip.id),db.from('flights').select('*').eq('trip_id',trip.id).order('sort_order'),
    db.from('trip_notes').select('*').eq('trip_id',trip.id).order('created_at',{ascending:false}),db.from('expenses').select('*').eq('trip_id',trip.id).order('spent_on',{ascending:false}),
    db.from('trip_tasks').select('*').eq('trip_id',trip.id).order('sort_order'),db.from('place_options').select('*').order('sort_order'),db.from('place_private').select('*'),db.from('reservation_private').select('*')]);
  const days=ds.data||[],ids=new Set(days.map(x=>x.id));DATA={session,trip,days,places:ps.data||[],items:(is.data||[]).filter(x=>ids.has(x.day_id)),reservations:rs.data||[],reservationPrivate:rps.data||[],flights:fs.data||[],notes:ns.data||[],expenses:es.data||[],tasks:ts.data||[],placeOptions:pos.data||[],placePrivate:pps.data||[]};
  dayId=dayId&&ids.has(dayId)?dayId:days[0]?.id;render();
}
function login(){root.className='login';root.innerHTML=`<section><a class="brand" href="index.html">HOKKAIDO 2026</a><h1>여행 관리자</h1><p>일정과 예약, 여행 메모와 비용을 안전하게 관리해요.</p><form id="login"><label>관리자 이메일<input name="email" type="email" value="amy9876@naver.com" required></label><button>이메일로 로그인 링크 받기</button></form><div id="msg"></div><small>등록된 관리자 이메일만 수정할 수 있습니다.</small></section>`;document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const email=new FormData(e.target).get('email'),m=document.querySelector('#msg');m.className='message';m.textContent='로그인 링크를 보내고 있어요…';const{error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:location.href.split('#')[0]}});m.textContent=error?'전송하지 못했어요: '+error.message:'이메일로 보낸 로그인 링크를 눌러주세요.'}}
function denied(email){root.className='login';root.innerHTML=`<section><h1>접근 권한이 없습니다</h1><p>${esc(email)}은 관리자로 등록되지 않았어요.</p><button id="out">다른 계정으로 로그인</button></section>`;document.querySelector('#out').onclick=()=>db.auth.signOut()}
function render(){root.className='workspace';root.innerHTML=`<aside class="side"><a class="brand" href="index.html">HOKKAIDO 2026</a><p>관리 중인 여행</p><strong>${esc(DATA.trip.title)}</strong><nav class="primary-nav">${[['operations','준비 · 현장 체크'],['places','장소 보관함'],['schedule','일정 관리'],['notes','방문 기록'],['expenses','여행 비용']].map(x=>`<button data-tab="${x[0]}" class="${tab===x[0]?'active':''}">${x[1]}</button>`).join('')}</nav><nav class="fixed-nav"><small>확정 정보</small>${[['flights','항공편'],['reservations','예약 정보']].map(x=>`<button data-tab="${x[0]}" class="${tab===x[0]?'active':''}">${x[1]}</button>`).join('')}</nav><footer><small>${esc(DATA.session.user.email)}</small><button id="out">로그아웃</button></footer></aside><section class="content"><header><h1>${{operations:'준비 · 현장 체크',places:'장소 보관함',schedule:'일정 관리',flights:'항공편 관리',reservations:'예약 확인',notes:'방문 기록',expenses:'여행비 통계'}[tab]}</h1><a href="index.html" target="_blank">가족 화면 보기 ↗</a></header>${message?`<div class="message">${esc(message)}</div>`:''}<div id="panel">${panel()}</div></section>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;message='';render()});document.querySelector('#out').onclick=()=>db.auth.signOut();bind()}
function panel(){return tab==='operations'?operations():tab==='places'?placesLibrary():tab==='schedule'?schedule():tab==='flights'?flights():tab==='reservations'?reservations():tab==='notes'?notes():expenses()}
const placeFor=i=>DATA.places.find(p=>p.id===i.place_id)||{};
function routeUrl(items){const p=items.map(placeFor).filter(x=>x.name||x.address);if(!p.length)return'';if(p.length===1)return p[0].map_url||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p[0].address||p[0].name)}`;const q=x=>encodeURIComponent(x.address||x.name),parts=[`origin=${q(p[0])}`,`destination=${q(p.at(-1))}`];if(p.length>2)parts.push(`waypoints=${p.slice(1,-1).map(x=>encodeURIComponent(x.address||x.name)).join('%7C')}`);return`https://www.google.com/maps/dir/?api=1&${parts.join('&')}&travelmode=driving`}
function timing(i={}){return`<div class="timing-fields"><label>시작 시간<input name="start_time" type="time" value="${(i.start_time||'').slice(0,5)}"></label><label>이동 시간(분)<input name="travel_minutes" type="number" min="0" value="${i.travel_minutes??''}" placeholder="예: 40"></label><label>머무는 시간(분)<input name="stay_minutes" type="number" min="0" value="${i.stay_minutes??''}" placeholder="예: 60"></label></div>`}
function placeFields(p={}){return`<div class="place-fields"><label>장소 이름<input name="place_name" value="${esc(p.name||'')}" placeholder="예: 오도리공원"></label><label>Google 지도 링크<input name="map_url" type="url" value="${esc(p.map_url||'')}" placeholder="https://maps.google.com/…"></label><label>사진 링크<input name="image_url" type="url" value="${esc(p.image_url||'')}" placeholder="출처가 명확한 이미지 URL"></label></div>`}
function basics(i={}){return`<div class="main-fields"><label>일정 이름<input name="title" value="${esc(i.title||'')}" required placeholder="가족 화면에 보일 이름"></label><label>이동 방법<select name="transport_mode">${[['car','자동차'],['walk','도보'],['train','기차'],['plane','비행기']].map(x=>`<option value="${x[0]}" ${i.transport_mode===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select></label><label>상태<select name="status">${[['planned','예정'],['confirmed','확정'],['completed','완료'],['skipped','건너뜀']].map(x=>`<option value="${x[0]}" ${i.status===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select></label></div>`}
const placeStatus={confirmed:'확정',candidate:'후보',excluded:'제외',visited:'방문 완료'};
const dayTag=n=>`trip-day:${n}`;
function placeDayNumbers(p){const manual=(p.tags||[]).map(x=>String(x).match(/^trip-day:(\d+)$/)?.[1]).filter(Boolean).map(Number),linked=DATA.items.filter(x=>x.place_id===p.id).map(x=>DATA.days.find(d=>d.id===x.day_id)?.day_number).filter(Boolean);return[...new Set([...manual,...linked])].sort()}
function placeDayBadges(p){const nums=placeDayNumbers(p);return nums.length?nums.map(n=>`<span>8월 ${27+n}일 · DAY ${n}</span>`).join(''):'<span class="undated">날짜 미정</span>'}
function placeLibraryFields(p={}){const priv=DATA.placePrivate.find(x=>x.place_id===p.id)||{},selected=placeDayNumbers(p);return`<div class="place-library-grid"><fieldset class="wide place-day-picker"><legend>사용할 여행 날짜</legend>${DATA.days.map(d=>`<label><input type="checkbox" name="place_days" value="${d.day_number}" ${selected.includes(d.day_number)?'checked':''}><span>${d.trip_date.slice(5).replace('-','월 ')}일 · DAY ${d.day_number}</span></label>`).join('')}<small>여러 날에 들를 후보라면 복수로 선택할 수 있어요.</small></fieldset><label>상태<select name="candidate_status">${Object.entries(placeStatus).map(([k,v])=>`<option value="${k}" ${p.candidate_status===k?'selected':''}>${v}</option>`).join('')}</select></label><label>분류<select name="category">${[['restaurant','음식점'],['cafe','카페'],['dessert','간식'],['shopping','쇼핑'],['sight','관광'],['nature','자연'],['station','교통'],['hotel','숙소'],['place','기타']].map(([k,v])=>`<option value="${k}" ${p.category===k?'selected':''}>${v}</option>`).join('')}</select></label><label>위도<input name="latitude" type="number" step="any" value="${p.latitude??''}"></label><label>경도<input name="longitude" type="number" step="any" value="${p.longitude??''}"></label><label class="wide">가족에게 보이는 짧은 추천<input name="public_tip" value="${esc(p.public_tip||'')}" placeholder="예: 산책 중 라테를 마시며 잠깐 쉬기 좋아요."></label><label class="wide">Google 지도 링크<input name="map_url" type="url" value="${esc(p.map_url||'')}"></label><label class="wide">관리자 메모<textarea name="admin_note" rows="2" placeholder="웨이팅, 후보로 둔 이유 등">${esc(priv.admin_note||'')}</textarea></label><label class="wide">주문 추천<textarea name="recommended_order" rows="2">${esc(priv.recommended_order||'')}</textarea></label><label>추천 시간대<input name="suggested_window" value="${esc(priv.suggested_window||'')}" placeholder="예: 14:00~16:00"></label><label>예약 메모<input name="booking_note" value="${esc(priv.booking_note||'')}"></label></div>`}
function placeCard(p){const linked=DATA.items.some(x=>x.place_id===p.id),tags=(p.tags||[]).filter(x=>!String(x).startsWith('trip-day:')).map(x=>`<span>${esc(x)}</span>`).join(''),days=placeDayNumbers(p);return`<article class="place-library-card status-${p.candidate_status}" data-place-days="${days.join(',')||'undated'}"><header><div><div class="place-days">${placeDayBadges(p)}</div><small>${esc(p.category)} ${linked?'· 일정 연결':''}</small><h3>${esc(p.name)}</h3><div class="place-tags">${tags}</div></div><b>${placeStatus[p.candidate_status]||'후보'}</b></header>${p.public_tip?`<p>${esc(p.public_tip)}</p>`:''}<details><summary>상세 정보 관리</summary><form data-place-library="${p.id}">${placeLibraryFields(p)}<div class="form-actions"><button class="save">변경 저장</button>${p.map_url?`<a href="${esc(p.map_url)}" target="_blank">Google 지도 ↗</a>`:''}</div></form></details></article>`}
function placesLibrary(){const counts=Object.keys(placeStatus).map(k=>[k,DATA.places.filter(x=>(x.candidate_status||'candidate')===k).length]);const order={confirmed:0,candidate:1,visited:2,excluded:3},places=[...DATA.places].sort((a,b)=>(placeDayNumbers(a)[0]??9)-(placeDayNumbers(b)[0]??9)||(order[a.candidate_status]??1)-(order[b.candidate_status]??1)||a.name.localeCompare(b.name,'ko'));return`<div class="place-library-intro"><div><small>Google Maps 후보 원본 → 여행용 장소 보관함</small><h2>확정 장소와 후보를 한곳에서 관리해요.</h2><p>날짜별로 후보를 나누고, 일정에 연결된 장소는 사용 날짜를 자동으로 표시합니다.</p></div><div class="place-counts">${counts.map(([k,n])=>`<span><b>${n}</b>${placeStatus[k]}</span>`).join('')}</div></div><div class="place-filter place-day-filter"><b>여행 날짜</b><button data-day-filter="all" class="active">전체 날짜</button>${DATA.days.map(d=>`<button data-day-filter="${d.day_number}">8월 ${d.trip_date.slice(8)}일</button>`).join('')}<button data-day-filter="undated">날짜 미정</button></div><div class="place-filter place-status-filter"><b>장소 상태</b>${Object.entries(placeStatus).map(([k,v])=>`<button data-place-filter="${k}">${v}</button>`).join('')}<button data-place-filter="all" class="active">전체</button></div><div class="place-library-list">${places.map(placeCard).join('')}</div>`}
function schedule(){const items=DATA.items.filter(x=>x.day_id===dayId).sort((a,b)=>a.sort_order-b.sort_order),route=routeUrl(items);return`<div class="tabs">${DATA.days.map(d=>`<button data-day="${d.id}" class="${d.id===dayId?'active':''}">DAY ${d.day_number} · ${d.trip_date.slice(5).replace('-','.')}</button>`).join('')}</div><div class="schedule-toolbar"><div><strong>${items.length}개의 일정</strong><span>시작·이동·체류 시간을 가족 화면과 함께 관리해요.</span></div>${route?`<a class="route-link" href="${esc(route)}" target="_blank">오늘 전체 경로 지도에서 보기 ↗</a>`:''}</div><details class="new-item"><summary>＋ 새 일정 추가</summary><form id="new-schedule" class="schedule-form"><h2>새 여행지와 일정</h2>${timing()}${basics()}<label>가족에게 보이는 설명<textarea name="description" rows="3"></textarea></label>${placeFields()}<button class="save">일정 추가하기</button></form></details><div class="panel schedule-list">${items.length?items.map(card).join(''):'<div class="empty">아직 일정이 없어요. 새 일정을 추가해 주세요.</div>'}</div>`}
function card(i){const p=placeFor(i);return`<article class="schedule-card"><div class="schedule-card-head"><b>${i.sort_order}</b><div><h2>${esc(i.title)}</h2><p>${esc(p.name||'장소 정보 미등록')}</p></div>${p.image_url?`<img src="${esc(p.image_url)}" alt="" loading="lazy">`:''}</div><form class="schedule-form" data-edit="${i.id}" data-place="${i.place_id||''}">${timing(i)}${basics(i)}<label>가족에게 보이는 설명<textarea name="description" rows="3">${esc(i.description||'')}</textarea></label>${placeFields(p)}<div class="form-actions"><button class="save">변경 저장</button>${p.map_url?`<a href="${esc(p.map_url)}" target="_blank">Google 지도 열기 ↗</a>`:''}<button type="button" class="delete" data-delete="${i.id}">일정 삭제</button></div></form></article>`}
function flightFields(f={}){return`<div class="flight-form-grid"><label>항공사<input name="airline" value="${esc(f.airline||'')}" placeholder="예: Jin Air" required></label><label>편명<input name="flight_number" value="${esc(f.flight_number||'')}" placeholder="예: LJ 301" required></label><label>운항<select name="is_nonstop"><option value="true" ${f.is_nonstop!==false?'selected':''}>직항</option><option value="false" ${f.is_nonstop===false?'selected':''}>경유</option></select></label><label>출발 공항 코드<input name="departure_code" value="${esc(f.departure_code||'')}" placeholder="ICN" maxlength="3" required></label><label>출발 공항 이름<input name="departure_airport" value="${esc(f.departure_airport||'')}" placeholder="Seoul Incheon International Airport"></label><label>출발 날짜<input name="departure_date" type="date" value="${f.departure_date||'2026-08-28'}" required></label><label>출발 시간<input name="departure_time" type="time" value="${(f.departure_time||'').slice(0,5)}" required></label><label>도착 공항 코드<input name="arrival_code" value="${esc(f.arrival_code||'')}" placeholder="CTS" maxlength="3" required></label><label>도착 공항 이름<input name="arrival_airport" value="${esc(f.arrival_airport||'')}" placeholder="New Chitose Airport"></label><label>도착 날짜<input name="arrival_date" type="date" value="${f.arrival_date||'2026-08-28'}" required></label><label>도착 시간<input name="arrival_time" type="time" value="${(f.arrival_time||'').slice(0,5)}" required></label><label>상태<select name="status">${[['planned','예정'],['confirmed','확정'],['completed','탑승 완료'],['cancelled','취소']].map(x=>`<option value="${x[0]}" ${f.status===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select></label><label class="wide">항공사·예약 확인 링크<input name="booking_url" type="url" value="${esc(f.booking_url||'')}" placeholder="선택 입력"></label></div>`}
function flightPreview(f){return`<div class="flight-preview"><div class="flight-title"><strong>${esc(f.departure_code||'출발')} → ${esc(f.arrival_code||'도착')}</strong><span>${f.status==='confirmed'?'예약 확정':'일정 '+({planned:'예정',completed:'완료',cancelled:'취소'}[f.status]||'')}</span></div><div class="flight-route"><div class="carrier"><b>✈</b><strong>${esc(f.flight_number)}</strong><span>${esc(f.airline)}</span></div><div><b>${esc(f.departure_code)}</b><strong>${(f.departure_time||'').slice(0,5)}</strong><span>${f.departure_date||''}</span><small>${esc(f.departure_airport||'')}</small></div><div class="flight-arrow"><b>→</b><span>${f.is_nonstop?'직항':'경유'}</span></div><div><b>${esc(f.arrival_code)}</b><strong>${(f.arrival_time||'').slice(0,5)}</strong><span>${f.arrival_date||''}</span><small>${esc(f.arrival_airport||'')}</small></div></div></div>`}
function flights(){return`<div class="flight-admin-intro"><div><strong>가족이 한눈에 보는 항공 정보</strong><span>예약번호와 결제정보는 이 화면에 저장하지 않아요.</span></div></div><details class="new-item" ${DATA.flights.length?'':'open'}><summary>＋ 항공편 등록</summary><form id="new-flight" class="schedule-form"><h2>새 항공편</h2>${flightFields()}<button class="save">항공편 저장</button></form></details><div>${DATA.flights.map(f=>`<article class="flight-editor">${flightPreview(f)}<details><summary>항공편 정보 수정</summary><form class="schedule-form" data-flight-edit="${f.id}">${flightFields(f)}<div class="form-actions"><button class="save">변경 저장</button><button type="button" class="delete" data-flight-delete="${f.id}">항공편 삭제</button></div></form></details></article>`).join('')}</div>`}
const taskLabels={preparation:'여행 전 준비',reservation:'예약·문의',day_briefing:'당일 챙길 것',fallback:'대안 플랜'};
const priorityLabels={normal:'일반',important:'중요',critical:'필수'};
function taskFields(t={}){return`<div class="task-form-grid"><label>종류<select name="task_type">${Object.entries(taskLabels).map(([k,v])=>`<option value="${k}" ${t.task_type===k?'selected':''}>${v}</option>`).join('')}</select></label><label>중요도<select name="priority">${Object.entries(priorityLabels).map(([k,v])=>`<option value="${k}" ${t.priority===k?'selected':''}>${v}</option>`).join('')}</select></label><label>준비 마감일<input name="due_date" type="date" value="${t.due_date||''}"></label><label>사용할 여행 날짜<input name="trip_date" type="date" min="2026-08-28" max="2026-08-30" value="${t.trip_date||''}"></label><label class="wide">할 일 제목<input name="title" value="${esc(t.title||'')}" required placeholder="예: 스시집에 전화 예약하기"></label><label class="wide">해야 할 내용<textarea name="details" rows="3" placeholder="언제, 무엇을 준비하고 확인해야 하는지 적어요.">${esc(t.details||'')}</textarea></label><label class="wide">문의할 문구<textarea name="inquiry_script" rows="3" placeholder="전화나 메시지로 그대로 읽을 내용을 적어요.">${esc(t.inquiry_script||'')}</textarea></label><label class="wide">일정이 틀어질 때 대안<textarea name="fallback_plan" rows="3" placeholder="예약 실패, 지연, 우천 시 대안을 적어요.">${esc(t.fallback_plan||'')}</textarea></label><label class="wide">예약·확인 링크<input name="action_url" type="url" value="${esc(t.action_url||'')}" placeholder="선택 입력"></label></div>`}
function taskCard(t){const day=DATA.days.find(d=>d.trip_date===t.trip_date),dateLabel=day?`DAY ${day.day_number} · ${day.trip_date.slice(5).replace('-','.')}`:t.due_date?`${t.due_date.slice(5).replace('-','.')}까지`:'날짜 미정';return`<article class="task-card ${t.is_completed?'done':''} priority-${t.priority}"><button class="task-check" data-task-check="${t.id}" aria-label="완료 상태 변경">${t.is_completed?'✓':''}</button><div class="task-body"><div class="task-meta"><span>${esc(taskLabels[t.task_type])}</span><span>${esc(priorityLabels[t.priority])}</span><time>${dateLabel}</time></div><h3>${esc(t.title)}</h3>${t.details?`<p>${esc(t.details)}</p>`:''}${t.inquiry_script?`<details><summary>문의할 내용</summary><blockquote>${esc(t.inquiry_script)}</blockquote></details>`:''}${t.fallback_plan?`<details><summary>대안 보기</summary><p>${esc(t.fallback_plan)}</p></details>`:''}<div class="task-actions">${t.action_url?`<a href="${esc(t.action_url)}" target="_blank">확인 페이지 ↗</a>`:''}<button data-task-edit="${t.id}">수정</button><button class="delete" data-task-delete="${t.id}">삭제</button></div><form class="task-edit" data-task-form="${t.id}" hidden>${taskFields(t)}<div class="form-actions"><button class="save">변경 저장</button><button type="button" data-task-cancel="${t.id}">닫기</button></div></form></div></article>`}
function taskGroup(title,subtitle,tasks){return`<section class="task-section"><header><div><h2>${title}</h2><p>${subtitle}</p></div><strong>${tasks.filter(x=>x.is_completed).length}/${tasks.length}</strong></header>${tasks.length?tasks.map(taskCard).join(''):'<div class="empty">등록된 항목이 없어요.</div>'}</section>`}
function operations(){const before=DATA.tasks.filter(x=>!x.trip_date),byDay=DATA.days.map(d=>[d,DATA.tasks.filter(x=>x.trip_date===d.trip_date)]),open=DATA.tasks.filter(x=>!x.is_completed).length;return`<div class="operations-hero"><div><small>여행 운영 보드</small><h2>출발 전에 준비하고,<br>당일에는 이것만 확인해요.</h2><p>이 내용은 로그인한 관리자에게만 보이며 가족 화면에는 표시되지 않습니다.</p></div><div><span>남은 체크</span><strong>${open}</strong><small>전체 ${DATA.tasks.length}개</small></div></div><details class="new-item task-new"><summary>＋ 새 체크 항목 추가</summary><form id="new-task" class="schedule-form"><h2>준비·예약·대안 등록</h2>${taskFields()}<button class="save">체크 항목 저장</button></form></details>${taskGroup('여행 전 준비함','예약 마감, 전화 문의, 서류처럼 출발 전에 끝낼 일을 모아요.',before)}${byDay.map(([d,t])=>taskGroup(`DAY ${d.day_number} 당일 브리핑`,`${d.trip_date.replaceAll('-','.')} · 일정 시작 전 가족에게 안내할 준비물과 대안`,t)).join('')}`}
function reservations(){const done=DATA.reservations.filter(x=>['booked','paid'].includes(x.status)).length;return`<div class="panel"><div class="cards"><article><span>전체 예약</span><strong>${DATA.reservations.length}</strong></article><article><span>완료</span><strong>${done}</strong></article><article><span>확인 필요</span><strong>${DATA.reservations.length-done}</strong></article></div>${DATA.reservations.map(x=>{const p=DATA.reservationPrivate.find(v=>v.reservation_id===x.id)||{};return`<article class="reservation reservation-detail"><div class="reservation-main"><div><small>${esc(x.provider||'예약처 미정')}</small><h3>${esc(x.title)}</h3><p>${esc(x.public_note||'')}</p></div><div class="reservation-actions"><select data-reservation="${x.id}">${[['needed','예약 필요'],['considering','확인 중'],['booked','예약 완료'],['paid','결제 완료'],['cancelled','취소']].map(o=>`<option value="${o[0]}" ${x.status===o[0]?'selected':''}>${o[1]}</option>`).join('')}</select>${x.booking_url?`<a href="${esc(x.booking_url)}" target="_blank">예약 확인·변경 ↗</a>`:''}</div></div>${p.confirmation_code||p.contact_name||p.contact_phone||p.private_note?`<div class="reservation-private"><strong>관리자 전용</strong><dl>${p.confirmation_code?`<div><dt>예약번호</dt><dd>${esc(p.confirmation_code)}</dd></div>`:''}${p.contact_name?`<div><dt>예약자</dt><dd>${esc(p.contact_name)}</dd></div>`:''}${p.contact_phone?`<div><dt>연락처</dt><dd>${esc(p.contact_phone)}</dd></div>`:''}</dl>${p.private_note?`<p>${esc(p.private_note)}</p>`:''}</div>`:''}</article>`}).join('')}</div>`}
function notes(){return`<div class="panel grid"><form id="note" class="form"><h2>새 여행 메모</h2><label>관련 일정<select name="itinerary_item_id"><option value="">여행 전체</option>${DATA.items.map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join('')}</select></label><div class="row"><label>종류<select name="note_type"><option value="memory">방문 후기</option><option value="tip">다음 여행 팁</option><option value="change">변경 사항</option></select></label><label>평점<select name="rating"><option value="">없음</option>${[5,4,3,2,1].map(n=>`<option>${n}</option>`).join('')}</select></label></div><label>메모<textarea name="content" rows="7" required></textarea></label><button>메모 저장</button></form><div class="records"><h2>저장된 기록</h2>${DATA.notes.length?DATA.notes.map(x=>`<article class="record"><small>${esc(x.note_type)} ${x.rating?'· '+'★'.repeat(x.rating):''}</small><p>${esc(x.content)}</p><time>${new Date(x.created_at).toLocaleDateString('ko-KR')}</time></article>`).join(''):'<p>아직 기록이 없어요.</p>'}</div></div>`}
const cats={flight:'항공',hotel:'숙박',transport:'교통',food:'식비',shopping:'쇼핑',ticket:'입장료',insurance:'보험',etc:'기타'};
function expenses(){const total=DATA.expenses.reduce((s,x)=>s+Number(x.amount_krw||0),0),groups=Object.entries(cats).map(([k,v])=>[k,v,DATA.expenses.filter(x=>x.category===k).reduce((s,x)=>s+Number(x.amount_krw||0),0)]).filter(x=>x[2]);return`<div class="panel"><div class="expense-total"><span>현재 기록된 총 여행비</span><strong>${total.toLocaleString()}원</strong><p>항공·숙박·보험을 포함한 현재 금액입니다.</p></div><div class="grid" style="margin-top:15px"><form id="expense" class="form"><h2>비용 추가</h2><div class="row"><label>사용일<input type="date" name="spent_on" value="2026-08-28" required></label><label>분류<select name="category">${Object.entries(cats).map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select></label></div><label>내용<input name="description" required></label><label>금액(원)<input name="amount" type="number" min="0" required></label><button>비용 저장</button></form><div class="costs"><h2>항목별 통계</h2>${groups.map(x=>`<div><span>${x[1]}</span><i><b style="width:${Math.max(5,x[2]/total*100)}%"></b></i><strong>${x[2].toLocaleString()}원</strong></div>`).join('')}</div></div><div class="expense-list">${DATA.expenses.map(x=>`<div><time>${x.spent_on}</time><span>${esc(x.description)}</span><b>${Number(x.amount_krw).toLocaleString()}원</b></div>`).join('')}</div></div>`}
function formValues(f){const v=Object.fromEntries(new FormData(f)),place={name:v.place_name.trim(),map_url:v.map_url.trim()||null,image_url:v.image_url.trim()||null};delete v.place_name;delete v.map_url;delete v.image_url;v.start_time=v.start_time||null;v.travel_minutes=v.travel_minutes===''?null:Number(v.travel_minutes);v.stay_minutes=v.stay_minutes===''?null:Number(v.stay_minutes);return{v,place}}
function flightValues(f){const v=Object.fromEntries(new FormData(f));v.departure_code=v.departure_code.toUpperCase();v.arrival_code=v.arrival_code.toUpperCase();v.is_nonstop=v.is_nonstop==='true';v.booking_url=v.booking_url||null;return v}
function taskValues(f){const v=Object.fromEntries(new FormData(f));v.due_date=v.due_date||null;v.trip_date=v.trip_date||null;v.action_url=v.action_url||null;return v}
function placeLibraryValues(f){const data=new FormData(f),v=Object.fromEntries(data),current=DATA.places.find(p=>p.id===f.dataset.placeLibrary),priv={admin_note:v.admin_note||null,recommended_order:v.recommended_order||null,suggested_window:v.suggested_window||null,booking_note:v.booking_note||null};delete v.admin_note;delete v.recommended_order;delete v.suggested_window;delete v.booking_note;delete v.place_days;v.tags=[...(current?.tags||[]).filter(x=>!String(x).startsWith('trip-day:')),...data.getAll('place_days').map(dayTag)];v.latitude=v.latitude===''?null:Number(v.latitude);v.longitude=v.longitude===''?null:Number(v.longitude);v.public_tip=v.public_tip||null;v.map_url=v.map_url||null;return{v,priv}}
async function savePlace(id,p){if(id){const{error}=await db.from('places').update(p).eq('id',id);if(error)throw error;return id}if(!p.name)return null;const{data,error}=await db.from('places').insert({...p,trip_id:DATA.trip.id}).select('id').single();if(error)throw error;return data.id}
function bind(){
  document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{dayId=b.dataset.day;render()});
  const add=document.querySelector('#new-schedule');if(add)add.onsubmit=async e=>{e.preventDefault();try{const{v,place}=formValues(add),place_id=await savePlace(null,place),sort_order=Math.max(0,...DATA.items.filter(x=>x.day_id===dayId).map(x=>x.sort_order))+1,{error}=await db.from('itinerary_items').insert({...v,day_id:dayId,place_id,sort_order,is_published:true});if(error)throw error;message='새 일정을 추가했어요. 가족 화면에도 바로 반영됩니다.'}catch(e){message='일정을 추가하지 못했어요: '+e.message}await boot()};
  document.querySelectorAll('[data-edit]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();try{const{v,place}=formValues(f),place_id=await savePlace(f.dataset.place||null,place),{error}=await db.from('itinerary_items').update({...v,place_id}).eq('id',f.dataset.edit);if(error)throw error;message='일정을 저장했어요. 가족 화면에도 같은 내용이 보입니다.'}catch(e){message='저장하지 못했어요: '+e.message}await boot()});
  document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{const i=DATA.items.find(x=>x.id===b.dataset.delete);if(!confirm(`‘${i?.title||'이 일정'}’을 삭제할까요? 삭제한 일정은 되돌릴 수 없어요.`))return;const{error}=await db.from('itinerary_items').delete().eq('id',b.dataset.delete);message=error?'삭제하지 못했어요: '+error.message:'일정을 삭제했어요.';await boot()});
  const nf=document.querySelector('#new-flight');if(nf)nf.onsubmit=async e=>{e.preventDefault();const v=flightValues(nf),sort_order=Math.max(0,...DATA.flights.map(x=>x.sort_order))+1,{error}=await db.from('flights').insert({...v,trip_id:DATA.trip.id,sort_order,is_published:true});message=error?'항공편을 저장하지 못했어요: '+error.message:'항공편을 저장했어요. 가족 화면에도 바로 표시됩니다.';await boot()};
  document.querySelectorAll('[data-flight-edit]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const{error}=await db.from('flights').update(flightValues(f)).eq('id',f.dataset.flightEdit);message=error?'항공편을 수정하지 못했어요: '+error.message:'항공편 정보를 수정했어요.';await boot()});
  document.querySelectorAll('[data-flight-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('이 항공편을 삭제할까요?'))return;const{error}=await db.from('flights').delete().eq('id',b.dataset.flightDelete);message=error?'항공편을 삭제하지 못했어요: '+error.message:'항공편을 삭제했어요.';await boot()});
  document.querySelectorAll('[data-reservation]').forEach(s=>s.onchange=async()=>{await db.from('reservations').update({status:s.value,updated_at:new Date().toISOString()}).eq('id',s.dataset.reservation);message='예약 상태를 저장했어요.';await boot()});
  const nt=document.querySelector('#new-task');if(nt)nt.onsubmit=async e=>{e.preventDefault();const v=taskValues(nt),sort_order=Math.max(0,...DATA.tasks.map(x=>x.sort_order))+10,{error}=await db.from('trip_tasks').insert({...v,trip_id:DATA.trip.id,sort_order});message=error?'체크 항목을 저장하지 못했어요: '+error.message:'새 체크 항목을 저장했어요.';await boot()};
  document.querySelectorAll('[data-task-check]').forEach(b=>b.onclick=async()=>{const t=DATA.tasks.find(x=>x.id===b.dataset.taskCheck),done=!t.is_completed,{error}=await db.from('trip_tasks').update({is_completed:done,completed_at:done?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',t.id);message=error?'완료 상태를 바꾸지 못했어요: '+error.message:done?'준비 완료로 표시했어요.':'다시 확인할 항목으로 돌렸어요.';await boot()});
  document.querySelectorAll('[data-task-edit]').forEach(b=>b.onclick=()=>{const f=document.querySelector(`[data-task-form="${b.dataset.taskEdit}"]`);f.hidden=!f.hidden});
  document.querySelectorAll('[data-task-cancel]').forEach(b=>b.onclick=()=>document.querySelector(`[data-task-form="${b.dataset.taskCancel}"]`).hidden=true);
  document.querySelectorAll('[data-task-form]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const{error}=await db.from('trip_tasks').update({...taskValues(f),updated_at:new Date().toISOString()}).eq('id',f.dataset.taskForm);message=error?'체크 항목을 수정하지 못했어요: '+error.message:'체크 항목을 수정했어요.';await boot()});
  document.querySelectorAll('[data-task-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('이 체크 항목을 삭제할까요?'))return;const{error}=await db.from('trip_tasks').delete().eq('id',b.dataset.taskDelete);message=error?'체크 항목을 삭제하지 못했어요: '+error.message:'체크 항목을 삭제했어요.';await boot()});
  let placeFilter='all',placeDayFilter='all';const applyPlaceFilters=()=>document.querySelectorAll('.place-library-card').forEach(c=>{const statusOk=placeFilter==='all'||c.classList.contains('status-'+placeFilter),days=(c.dataset.placeDays||'').split(','),dayOk=placeDayFilter==='all'||days.includes(placeDayFilter);c.hidden=!(statusOk&&dayOk)});document.querySelectorAll('[data-place-filter]').forEach(b=>b.onclick=()=>{placeFilter=b.dataset.placeFilter;document.querySelectorAll('[data-place-filter]').forEach(x=>x.classList.toggle('active',x===b));applyPlaceFilters()});document.querySelectorAll('[data-day-filter]').forEach(b=>b.onclick=()=>{placeDayFilter=b.dataset.dayFilter;document.querySelectorAll('[data-day-filter]').forEach(x=>x.classList.toggle('active',x===b));applyPlaceFilters()});
  document.querySelectorAll('[data-place-library]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const{v,priv}=placeLibraryValues(f);const [a,b]=await Promise.all([db.from('places').update(v).eq('id',f.dataset.placeLibrary),db.from('place_private').upsert({...priv,place_id:f.dataset.placeLibrary,updated_at:new Date().toISOString()})]);message=a.error||b.error?'장소를 저장하지 못했어요: '+(a.error||b.error).message:'장소 상태와 메모를 저장했어요.';await boot()});
  const n=document.querySelector('#note');if(n)n.onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(n));v.trip_id=DATA.trip.id;v.itinerary_item_id=v.itinerary_item_id||null;v.rating=Number(v.rating)||null;await db.from('trip_notes').insert(v);message='메모를 저장했어요.';await boot()};
  const x=document.querySelector('#expense');if(x)x.onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(x));v.trip_id=DATA.trip.id;v.amount=Number(v.amount);v.amount_krw=v.amount;v.currency='KRW';await db.from('expenses').insert(v);message='비용을 저장했어요.';await boot()}
}
boot();
