(()=>{
  const ASSET='assets/guides/';
  let map=null,lastKey='';
  const routes={
    canal:{title:'오타루 운하 산책 상세 경로',note:'전체 약 1.3km · 순수 도보 약 25분. 사진과 휴식을 포함해 60~70분을 잡았어요.',points:[['오타루역',43.1974,140.9937,'10:41 도착'],['중앙통',43.1981,140.9978,'바다 방향'],['운하 플라자',43.1994,141.0013,'잠깐 휴식'],['운하 산책로',43.1990,141.0025,'남쪽으로'],['아사쿠사바시',43.1986,141.0037,'대표 사진 지점']]},
    dessert:{title:'사카이마치 디저트 산책 후보',note:'후보를 전부 방문할 필요는 없어요. 사람이 덜 붐비는 곳 1~2곳만 고르고 17:10까지 오타루역으로 돌아가요.',points:[['스시 나카무라',43.1904,141.0058,'점심 출발'],['르타오 본점',43.1908,141.0078,'치즈케이크'],['오르골당',43.1901,141.0077,'구경·기념품'],['롯카테이 오타루',43.1915,141.0070,'과자·선물'],['B3 COFFEE',43.1958,141.0024,'조용히 쉬기']]}
  };
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function mapGuide(kind){const r=routes[kind];return `<section class="detail-route" data-guide="${kind}"><header><div><p class="eyebrow dark">SELECTED SCHEDULE GUIDE</p><h2>${r.title}</h2></div><a href="${kind==='canal'?'https://www.google.com/maps/dir/?api=1&origin=Otaru+Station&destination=Asakusa+Bridge+Otaru+Canal&waypoints=Otaru+Canal+Plaza&travelmode=walking':'https://www.google.com/maps/dir/?api=1&origin=Sushi+Nakamura+Otaru&destination=Otaru+Station&waypoints=LeTAO+Main+Store%7COtaru+Music+Box+Museum%7CRokkatei+Otaru%7CB3+Coffee+Otaru&travelmode=walking'}" target="_blank" rel="noreferrer">Google Maps에서 열기 ↗</a></header><div class="guide-map" id="selected-guide-map"></div><ol>${r.points.map((x,i)=>`<li><b>${i+1}</b><span><strong>${esc(x[0])}</strong><small>${esc(x[3])}</small></span></li>`).join('')}</ol><p>${r.note}</p></section>`}
  function trainGuide(title){const returning=title.includes('복귀');return `<section class="detail-route train-guide" data-guide="train"><header><div><p class="eyebrow dark">JR TRAIN GUIDE</p><h2>${returning?'오타루에서 삿포로로 돌아오기':'JR 삿포로역에서 오타루 가기'}</h2></div><a href="https://www.jrhokkaido.co.jp/global/korean/travel/airport.html" target="_blank" rel="noreferrer">JR 공식 안내 ↗</a></header><div class="train-layout"><div class="guide-gallery"><figure><img src="${ASSET}jr-green-train.png" alt="초록색 띠가 있는 JR 홋카이도 열차"><figcaption>초록색 띠의 JR 열차와 ‘小樽(오타루)’ 행선지를 확인해요.</figcaption></figure><figure><img src="${ASSET}jr-ticket-machine.png" alt="JR 승차권과 Kitaca 충전 발매기"><figcaption><b>JR線きっぷ</b> 승차권 · <b>ICカード</b> 교통카드 · <b>チャージ</b> 충전</figcaption></figure></div><div class="train-steps"><span>탑승</span><strong>${returning?'小樽駅 오타루역':'札幌駅 삿포로역'}</strong><i>→</i><span>하차</span><strong>${returning?'札幌駅 삿포로역':'小樽駅 오타루역'}</strong><p>${returning?'17:30 쾌속 에어포트 156호 → 18:08 도착':'10:00 쾌속 에어포트 35호 → 10:41 도착'}</p><p>성인 편도 800엔 · Kitaca를 개찰구에 찍거나 발매기에서 승차권을 구입해요.</p></div></div></section>`}
  function draw(kind){if(map){map.remove();map=null}if(!routes[kind]||!window.L)return;const p=routes[kind].points,pts=p.map(x=>[x[1],x[2]]);map=L.map('selected-guide-map',{scrollWheelZoom:false,zoomControl:false});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);L.polyline(pts,{color:kind==='dessert'?'#bc6b3d':'#196fa8',weight:5}).addTo(map);p.forEach((x,i)=>L.marker([x[1],x[2]],{icon:L.divIcon({className:`detail-marker ${kind}`,html:`<b>${i+1}</b>`,iconSize:[28,28],iconAnchor:[14,14]})}).addTo(map).bindPopup(`<strong>${esc(x[0])}</strong><br>${esc(x[3])}`));map.fitBounds(pts,{padding:[28,28]})}
  function mount(){const day=document.querySelector('.day-tabs button.active strong')?.textContent,active=document.querySelector('.item.active .item-content strong')?.textContent||'',overview=document.querySelector('.route-overview'),head=document.querySelector('.journey-head');let key='none',html='';if(day==='29일'){if(active==='JR로 오타루 이동'||active==='삿포로 복귀와 쇼핑'){key='train:'+active;html=trainGuide(active)}else if(active==='오타루운하 산책'){key='canal';html=mapGuide('canal')}else if(active==='사카이마치 디저트 산책'){key='dessert';html=mapGuide('dessert')}}if(key===lastKey&&document.querySelector('.detail-route'))return;lastKey=key;document.querySelector('.detail-route')?.remove();if(map){map.remove();map=null}if(key==='none'||!overview||!head)return;head.insertAdjacentHTML('beforebegin',html);if(routes[key])requestAnimationFrame(()=>draw(key))}
  new MutationObserver(()=>requestAnimationFrame(mount)).observe(document.documentElement,{childList:true,subtree:true});
})();
