(()=>{
  const ASSET='assets/guides/';
  const IMG={
    ichigen:'https://www.hokkaido-airports.com/ja/new-chitose/assets/pages/special/airport-noodle/img/ph_146_2.jpg',
    keyaki:'https://tblg.k-img.com/restaurant/images/Rvw/317425/640x640_rect_9285e10882a09d080f5830e2f85e5723.jpg',
    ajisai:'https://tblg.k-img.com/restaurant/images/Rvw/312069/640x640_rect_9b80f3b674a025bb6ac8d811dec6a807.jpg',
    hien:'https://www.hokkaido-airports.com/ja/new-chitose/assets/pages/special/airport-noodle/img/ph_273_1.jpg',
    teshikaga:'https://www.hokkaido-airports.com/ja/new-chitose/assets/pages/special/airport-noodle/img/ph_244_1.jpg',
    shimukappu:'https://www.michi-no-eki.jp/sites/default/files/styles/stations_main/public/stations/de1994f3eece33d468ba8dd39b42ad80.jpg',
    parfait:'https://svcstrg.cld.navitime.jp/imgfile/02301_1503673_01.jpg',
    shikisaiMap:ASSET+'shikisai-course-map.png',
    norokko:'https://www.shikisainooka.jp/wp-content/themes/shikisainooka/images/greenseason/norimonoPh01.jpg',
    croquette:'https://www.shikisainooka.jp/wp-content/themes/shikisainooka/images/about/aboutRestaurant02.jpg',
    softcream:'https://www.shikisainooka.jp/wp-content/themes/shikisainooka/images/about/aboutRestaurant03.jpg',
    melon:'https://www.shikisainooka.jp/wp-content/themes/shikisainooka/images/about/aboutRestaurant04.jpg',
    bluepond:'https://www.biei-hokkaido.jp/wp3/wp-content/uploads/2023/11/bluepond-catch.jpg',
    bluepondMap:'https://www.biei-hokkaido.jp/wp3/wp-content/uploads/2024/11/blue-pond-entrance.jpg',
    shibukiMenu:'https://static.wixstatic.com/media/aaf248_327d64794e934bb6a5f06c4913bd348e~mv2.jpg/v1/fill/w_595%2Ch_842%2Cal_c%2Cq_85%2Cenc_avif%2Cquality_auto/S__506372102_0.jpg',
    kamaei:'https://api.mediacms.jp/uploads/Still0204_00018_03489663f4.jpg',
    musicbox:'https://rimage.gnst.jp/livejapan.com/public/img/spot/lj/00/07/lj0007819/lj0007819_5b1a65bdbbbec_main.jpg?20260401133201=&q=80',
    harriet:'https://sapporoagriculturalcollege.com/img/harriet/box.webp',
    yukipurin:'https://shopblog.dmdepart.jp/sapporo/uploads/images/resized/1000x0/sapporo/000321/000321/57d42b56.png',
    nakamuraSushi:'https://tblg.k-img.com/resize/640x640c/restaurant/images/Rvw/86453/86453261.jpg?api=v2&token=a9a5ea4',
    b3menu:'https://stat.ameba.jp/user_images/20230419/11/zaby-zaby/91/11/j/o1080144015272497573.jpg',
    b3food:'https://stat.ameba.jp/user_images/20230419/11/zaby-zaby/2c/e3/j/o1080144015272497560.jpg'
  };
  let map=null,lastKey='';
  const routes={
    canal:{title:'오타루 운하 30분 핵심 산책',note:'전체 약 1.1km · 역에서 중앙통을 따라 내려가 대표 사진 지점까지만 보는 압축 코스예요. 10:50에는 사카이마치 방향으로 출발해요.',points:[['오타루역',43.1974,140.9937,'10:15 도착'],['중앙통',43.1981,140.9978,'바다 방향 직진'],['운하 플라자',43.1994,141.0013,'외관만 빠르게'],['운하 교차점',43.1990,141.0025,'운하 첫 풍경'],['아사쿠사바시',43.1986,141.0037,'10:45 대표 사진']]},
    dessert:{title:'사카이마치 산책·오르골당·옥수수 확인',note:'오르골당을 본 뒤 우로코상회에서 삶은 옥수수 또는 퓨어화이트 재고를 확인해요. 16:00 오타루역 출발편을 예약했으므로 15:20에는 역 방향으로 출발해요.',points:[['스시 나카무라',43.1904,141.0058,'점심 후 출발'],['B3 COFFEE OTARU',43.1958,141.0024,'커피 테이크아웃'],['르타오 본점',43.1908,141.0078,'본점 한정만 확인'],['오타루 오르골당',43.1901,141.0077,'기념품·외관'],['우로코상회 사카이마치점',43.1888,141.0081,'옥수수 있으면 구매'],['오타루역',43.1974,140.9937,'15:40까지 도착']]}
  };
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const source=(href,label='공식 안내')=>`<a class="guide-source" href="${href}" target="_blank" rel="noreferrer">${label} ↗</a>`;
  const photo=(src,alt,caption)=>`<figure><img src="${src}" alt="${alt}" loading="lazy"><figcaption>${caption}</figcaption></figure>`;
  const frame=(type,title,body,link='')=>`<section class="detail-route rich-guide" data-guide="${type}"><header><div><p class="eyebrow dark">SELECTED SCHEDULE GUIDE</p><h2>${title}</h2></div>${link}</header>${body}</section>`;
  function airportGuide(){
    const links=`<div class="airport-map-links">${source('https://www.hokkaido-airports.com/ko/new-chitose/floormap/international/?floor=2F','국제선 2층 공식 지도')}${source('https://www.hokkaido-airports.com/ko/new-chitose/floormap/domestic/?floor=3F','국내선 3층 공식 지도')}${source('https://www.hokkaido-airports.com/en/new-chitose/access/rentacar/','렌터카 카운터 공식 안내')}</div>`;
    return frame('airport','입국장 → 라멘 → 닛폰렌터카 길찾기',`
      <div class="guide-callout"><b>기본안 · 부모님 식사 40분 확보</b><strong>11:00 착륙 → 12:00 전후 입국장 → 12:10 라멘도장 → 12:50 식사 종료 → 13:00 렌터카 카운터 → 13:10 전후 송영 → 13:25 영업소 → 13:30 인수 절차</strong><p>송영이 바로 연결되면 13:40 전후 실제 운전 출발을 예상해요. 예약 시각보다 약간 늦어질 가능성은 있으므로 카운터에서 먼저 예약번호를 확인합니다.</p></div>
      <div class="option-plans airport-delay-plans"><article><span>입국장을 12:15 이전에 나왔을 때</span><h3>기본안 그대로 진행</h3><p>라멘과 이동에 50분을 쓰고 13:00까지 렌터카 카운터에 도착해요. 부모님 식사는 40분 확보합니다.</p><b>13:30 인수 절차 · 13:40 전후 출발</b></article><article><span>입국장을 12:20 이후에 나왔을 때</span><h3>식사 전에 렌터카 지연 연락</h3><p>050-1712-2970으로 전화해 항공편·입국수속 지연과 예상 카운터 도착 시각을 알린 뒤, 식사를 35~40분 하고 이동해요.</p><b>연락 없이 1시간 이상 늦지 않기</b></article></div>
      <h3>공항 안에서 따라갈 표지판</h3>
      <div class="airport-wayfinding">
        <article><b>1</b><small>국제선 2F</small><h4>입국수속·수하물·세관</h4><p>도착 로비로 나오면 <strong>国内線 / Domestic Terminal</strong> 표지판을 찾고 국내선 연결 방향으로 이동해요.</p><span>찾을 글자: 国内線 · 連絡施設</span></article>
        <i>→</i>
        <article><b>2</b><small>연결 통로</small><h4>국내선 터미널로 이동</h4><p>무빙워크가 있는 연결시설을 통과해 국내선 건물로 가요. 부모님과 짐이 있으니 엘리베이터를 우선 이용합니다.</p><span>예상 도보 10분 안팎</span></article>
        <i>→</i>
        <article><b>3</b><small>국내선 3F</small><h4>北海道ラーメン道場</h4><p>국내선 건물에서 <strong>3F Restaurants</strong> 표지판을 따라 올라가 ‘홋카이도 라멘도장’ 입구를 찾아요.</p><span>12:10~12:50 식사 목표</span></article>
        <i>→</i>
        <article><b>4</b><small>국내선 1F</small><h4>도착구 3번 부근 렌터카</h4><p>식사 후 1층으로 내려가 <strong>到着口3 / Arrival Gate 3</strong>와 <strong>レンタカー / Car Rental</strong> 표지판을 따라가요.</p><span>닛폰렌터카 카운터 찾기</span></article>
        <i>→</i>
        <article><b>5</b><small>무료 송영</small><h4>카운터 접수 후 영업소 이동</h4><p>카운터에서 접수하면 버스로 신치토세공항 영업소까지 이동해요. 편도 약 10~15분이며 공항 터미널에서는 차량을 받을 수 없어요.</p><span>카운터가 비면 비치된 직통전화 사용</span></article>
      </div>${links}
      <h3>국내선 3층 홋카이도 라멘도장 추천 3곳</h3><div class="guide-cards food-cards"><article>${photo(IMG.keyaki,'게야키 미소라멘','사진: Tabelog · 신치토세공항점')}<h4>1순위 · 게야키</h4><p>3종 된장을 섞은 깊은 국물과 중간 굵기 꼬불면의 정통 삿포로 미소라멘이에요.</p><b>味噌ラーメン · ¥870</b></article><article>${photo(IMG.ajisai,'아지사이 시오라멘','사진: Tabelog · 신치토세공항점')}<h4>2순위 · 아지사이</h4><p>맑고 가벼운 하코다테식 소금 국물. 부모님이 진한 된장 국물이 부담스러울 때 좋아요.</p><b>味彩塩拉麺 · ¥950</b></article><article>${photo(IMG.ichigen,'에비소바 이치겐의 새우 소금 라멘','공항 공식 사진')}<h4>3순위 · 에비소바 이치겐</h4><p>새우 향을 진하게 느끼고 싶을 때 선택해요. 대기가 길면 1·2순위로 바로 바꿉니다.</p><b>そのまま えびしお · ¥950</b></article></div>
      <div class="guide-note"><b>점심 시간 기준</b><p>정상 도착이면 12:10~12:50을 식사 시간으로 확보해요. 게야키 대기가 10분 이상이면 아지사이 또는 이치겐으로 바꾸되 식사 자체를 서두르지는 않습니다. 입국수속이 1시간 더 걸리면 닛폰렌터카에 먼저 전화하고, 안내받은 인수 가능 시각에 맞춰 이후 비에이 일정을 조정합니다.</p></div>
      <h3>닛폰렌터카 카운터에서 할 일</h3><div class="guide-steps"><span><b>1</b>예약번호 T06394와 예약자 ‘チョンスンジェ’ 확인</span><span><b>2</b>여권·한국 운전면허증·국제운전면허증·결제카드 제시</span><span><b>3</b>관리자 페이지 ‘예약 정보’에서 원문 예약확인서 열기</span><span><b>4</b>카운터가 비어 있으면 직통전화, 문의 전화는 050-1712-2970</span><span><b>5</b>송영버스 승차 → 영업소에서 계약·차량 확인 → 출발</span></div>
    `,source('https://store.nipponrentacar.co.jp/b/nrs/info/810034','닛폰렌터카 신치토세공항점 공식 안내'))
  }
  function shimukappuGuide(){return frame('shimukappu','시무캇푸 15분 회복 정차',`<div class="guide-callout"><b>14:45 전후 도착 예상</b><strong>화장실 5분 · 간식/농산물 7분 · 승차 3분</strong><p>매장 운영은 9:00~18:00. 15:00에 다시 출발해야 시키사이노오카 관람 시간을 지킬 수 있어요.</p></div><div class="guide-gallery two">${photo(IMG.parfait,'시무캇피 도라야키 파르페','시무캇피 도라야키 파르페 · 공식 등록가 ¥400')}${photo(IMG.shimukappu,'자연체감 시무캇푸 휴게소','농산물·특산품은 당일 입고 여부를 확인해요.')}</div><div class="guide-note"><b>빠르게 살 것</b><p>파르페 1~2개를 나눠 먹고, 옥수수·감자·여름 채소가 보이면 차에서 먹을 만큼만 구입해요. 농산물은 계절·입고 상황에 따라 없을 수 있습니다.</p></div>`,source('https://www.michi-no-eki.jp/stations/views/18852','전국 도로휴게소 공식 안내'))}
  function shikisaiGuide(){return frame('shikisai','시키사이노오카 65분 선택 코스',`<div class="guide-gallery map-feature">${photo(IMG.shikisaiMap,'시키사이노오카 공식 원내 지도','입구·매점·전망 꽃밭을 확인하는 공식 원내 지도')}</div><div class="transport-card">${photo(IMG.norokko,'시키사이노오카 노롯코 트랙터 버스','노롯코호 · 약 15분 원내 일주')}<div><h3>부모님과는 노롯코호를 우선 추천</h3><p>성인 ¥500 · 현금 결제. 걷는 양을 줄이면서 꽃밭과 언덕 풍경을 볼 수 있어요.</p><small>카트는 4인 15분 ¥2,500, 운전면허 필요 · 알파카 목장 성인 ¥500</small></div></div><h3>도착 후 컨디션에 따라 하나만 선택</h3><div class="course-list"><article><b>A · 편안한 기본 코스</b><span>매점 간식 15분 → 노롯코 15분 → 전망 꽃밭·사진 25분 → 화장실·출차 10분</span><strong>총 65분 · 가장 추천</strong></article><article><b>B · 꽃밭 도보 코스</b><span>정문 꽃밭 15분 → 전망 꽃밭 25분 → 간식 15분 → 화장실·출차 10분</span><strong>총 65분 · 날씨가 선선할 때</strong></article><article><b>C · 알파카 포함 코스</b><span>알파카 20분 → 노롯코 15분 → 간식 15분 → 이동·출차 15분</span><strong>총 65분 · 꽃밭 도보는 최소화</strong></article></div><h3>매점에서 살 것</h3><div class="guide-cards snack-cards"><article>${photo(IMG.softcream,'라벤더와 메론 소프트아이스크림','소프트크림 · ミルク/ラベンダー/メロン')}<b>라벤더 소프트</b><span>¥450 · 1~2개 나눠 먹기</span></article><article>${photo(IMG.croquette,'언덕 감자 고로케','丘のじゃがいもコロッケ')}<b>감자 고로케</b><span>¥180 · 남작/키타아카리</span></article><article>${photo(IMG.melon,'스노우 멜론','スノーメロン')}<b>스노우 멜론</b><span>공식 안내 ¥2,000 · 4명이 나눠 먹기</span></article></div><div class="guide-note"><b>찐 옥수수</b><p>당일 판매하면 1~2개만 추가해요. 계절 상품이므로 없으면 시무캇푸에서 산 옥수수로 대체합니다.</p></div>`,source('https://www.shikisainooka.jp/green/','시키사이노오카 공식 안내'))}
  function bluePondGuide(){return frame('bluepond','청의호수 25분 산책',`<div class="guide-gallery two map-gallery">${photo(IMG.bluepondMap,'청의호수 승용차 주차장 입구 안내도','승용차는 일반 차량 입구로 진입')}${photo(IMG.bluepond,'비에이 청의호수','주차장 → 산책로 → 연못 가장자리 관람')}</div><div class="guide-steps"><span><b>1</b>17:20 일반 승용차 입구로 진입하고 주차권 받기</span><span><b>2</b>주차장에서 청의호수까지 평탄한 길로 약 5분 이동</span><span><b>3</b>연못 가장자리에서 10~12분 관람·사진</span><span><b>4</b>출구 혼잡을 피하려면 사전정산 후 17:45 출발</span></div><div class="guide-note"><b>2026년 8월 승용차 주차료</b><p>¥1,000 · 주차장 운영 7:00~19:00. 청의호수 자체는 별도 입장권이 없어요.</p></div>`,source('https://www.biei-hokkaido.jp/ja/shirogane-blue-pond','미에이 관광협회 공식 안내'))}
  function splitGuide(){return frame('split','호텔 하차와 렌터카 반납 양동작전',`<div class="role-split"><article><span>가족 3명</span><h3>라젠트 스테이 앞 하차</h3><p>짐을 모두 내리고 호텔 체크인. 여권 4개와 예약자 이름을 준비해요.</p><b>로비에서 객실 확인 후 휴식</b></article><article><span>오빠</span><h3>닛폰렌터카 반납</h3><p>연료·차량 내부·소지품을 확인하고 삿포로역 앞점으로 반납해요.</p><b>반납 완료 후 호텔로 도보/택시 복귀</b></article></div><div class="guide-callout"><b>재합류 기준</b><strong>20:30까지 호텔 로비 또는 객실에서 합류</strong><p>21:00 시부키 예약에 늦지 않도록 20:40에는 호텔에서 함께 출발해요.</p></div>`)}
  function shibukiGuide(){return frame('shibuki','야키니쿠 시부키 주문 가이드',`<div class="menu-layout">${photo(IMG.shibukiMenu,'야키니쿠 시부키 공식 메뉴판','메뉴 이름을 사진과 대조해 주문해요.')}<div><h3>4인 첫 주문</h3><ol class="order-list"><li><b>極み厚切り超熟サガリ</b><span>극상 두툼 숙성 사가리 × 2</span></li><li><b>吊るし熟成牛タン</b><span>행잉 숙성 우설 × 1</span></li><li><b>和牛カルビ</b><span>와규 갈비 × 1</span></li><li><b>キムチ・もやしナムル</b><span>김치·숙주나물 각 1</span></li><li><b>肉厚しいたけ・塩玉ねぎ焼き</b><span>표고버섯·소금 양파 각 1</span></li></ol><p>먼저 사가리와 우설을 먹고, 부족하면 사가리 또는 당일 추천 살코기를 1~2접시 추가해요.</p></div></div><div class="guide-note"><b>제철 해산물 주문</b><p>“今日のおすすめの海鮮はありますか？”(쿄오노 오스스메노 카이센와 아리마스카?)라고 물어보고 1접시만 추가해요. 예상 총액은 관리자 페이지에서 확인합니다.</p></div>`,source('https://www.jingisukanyuuhi.com/shibuki','시부키 공식 메뉴'))}
  function dayOneGuide(title){if(title==='신치토세공항 도착')return['airport',airportGuide()];if(title==='미치노에키 시무캇푸 휴식')return['shimukappu',shimukappuGuide()];if(title==='시키사이노오카')return['shikisai',shikisaiGuide()];if(title==='청의호수 산책')return['bluepond',bluePondGuide()];if(title==='호텔 하차·렌터카 반납 동시 진행')return['split',splitGuide()];if(title==='야키니쿠 시부키 저녁')return['shibuki',shibukiGuide()];return['none','']}
  function mapGuide(kind){const r=routes[kind],url=kind==='canal'?'https://www.google.com/maps/dir/?api=1&origin=Otaru+Station&destination=Asakusa+Bridge+Otaru+Canal&waypoints=Otaru+Canal+Plaza&travelmode=walking':'https://www.google.com/maps/dir/?api=1&origin=Asakusa+Bridge+Otaru+Canal&destination=Sushi+Nakamura+Otaru&waypoints=Kamaei+Factory+Direct+Store%7CRokkatei+Otaru%7CLeTAO+Main+Store%7COtaru+Music+Box+Museum&travelmode=walking';const extras=kind==='dessert'?`<div class="buy-priority"><article class="must-buy"><small>오타루에서 우선</small>${photo(IMG.kamaei,'카마에이 빵롤','사진: Sitakke · 가격은 카마에이 공식 2026년 확인가')}<h3>카마에이 갓 튀긴 빵롤</h3><b>パンロール · ¥264</b><p>삿포로점에도 있지만 공장직매점에서 갓 튀긴 것을 바로 먹는 경험을 우선해요. 냉장 3일이라 선물보다는 현장 간식용입니다.</p>${source('https://kamaei.co.jp/about-panroll/','가격·판매점 공식 안내')}</article><article class="must-buy"><small>본점 한정 확인</small><div class="text-photo">LeTAO<br><em>MAIN STORE</em></div><h3>르타오 본점 블렌드티</h3><b>カリヨンの音色</b><p>공식 안내에 본점 한정으로 표시된 홍차예요. 가격과 재고는 현장에서 확인하고, 일반 치즈케이크는 삿포로로 미뤄도 됩니다.</p>${source('https://www.letao.jp/shop/letao.php','르타오 본점 공식 안내')}</article><article><small>마음에 들면 현장 선택</small>${photo(IMG.musicbox,'오타루 오르골당 내부의 유리 오르골','사진: LIVE JAPAN · 제품별 가격 상이')}<h3>오타루 오르골당</h3><b>유리 오르골 · 가격 상이</b><p>디자인과 곡이 제품마다 달라요. 15분만 둘러보고 마음에 드는 것이 있을 때만 구입합니다.</p></article></div><div class="skip-later"><b>삿포로로 미뤄도 되는 것</b><span>르타오 일반 치즈케이크</span><span>롯카테이 포장 과자</span><span>카마에이 포장 어묵</span><p>다이마루 삿포로점 지하 1층에서도 살 수 있어 오타루 산책 시간을 지켜요.</p></div>`:'';return `<section class="detail-route ${kind==='dessert'?'rich-guide':''}" data-guide="${kind}"><header><div><p class="eyebrow dark">SELECTED SCHEDULE GUIDE</p><h2>${r.title}</h2></div><a href="${url}" target="_blank" rel="noreferrer">Google Maps에서 열기 ↗</a></header><div class="guide-map" id="selected-guide-map"></div><ol>${r.points.map((x,i)=>`<li><b>${i+1}</b><span><strong>${esc(x[0])}</strong><small>${esc(x[3])}</small></span></li>`).join('')}</ol><p>${r.note}</p>${extras}</section>`}
  function trainGuide(title){const returning=title.includes('삿포로');return `<section class="detail-route train-guide" data-guide="train"><header><div><p class="eyebrow dark">JR TRAIN GUIDE</p><h2>${returning?'오타루역에서 삿포로로 돌아오기':'JR 삿포로역에서 오타루 가기'}</h2></div><a href="https://www3.jrhokkaido.co.jp/webunkou/timetable.html?id=077" target="_blank" rel="noreferrer">JR 공식 시간표 ↗</a></header><div class="train-layout"><div class="guide-gallery"><figure><img src="${ASSET}jr-green-train.png" alt="초록색 띠가 있는 JR 홋카이도 열차"><figcaption>초록색 띠의 JR 열차와 행선지를 확인해요.</figcaption></figure><figure><img src="${ASSET}jr-ticket-machine.png" alt="JR 승차권과 Kitaca 충전 발매기"><figcaption><b>JR線きっぷ</b> 승차권 · <b>ICカード</b> 교통카드 · <b>チャージ</b> 충전</figcaption></figure></div><div class="train-steps"><span>탑승</span><strong>${returning?'小樽駅 오타루역':'札幌駅 삿포로역'}</strong><i>→</i><span>하차</span><strong>${returning?'札幌駅 삿포로역':'小樽駅 오타루역'}</strong><p>${returning?'사카이마치에서 오르골당과 거리를 구경한 뒤 오타루역으로 걸어가요. 15:50 전후 삿포로 직통 열차를 목표로 해요.':'11:30 특별쾌속 에어포트 53호 → 12:05 오타루 도착'}</p><p>Kitaca를 개찰구에 찍고 이용해요. 정확한 승강장과 다음 열차는 역 전광판에서 한 번 더 확인해요.</p></div></div></section>`}
  function sushiGuide(){return frame('nakamura','스시 나카무라 4인 주문 가이드',`<div class="menu-layout sushi-order">${photo(IMG.nakamuraSushi,'스시 나카무라 제철 니기리','사진: Tabelog 이용자 · 실제 구성은 당일 수급에 따라 달라져요.')}<div><h3>추천 조합</h3><ol class="order-list"><li><b>十一貫握り × 2</b><span>제철 니기리 11관 · 1인 ¥7,200</span></li><li><b>本日の丼もの × 2</b><span>오늘 가능한 카이센동·제철 해산물 덮밥의 종류와 가격을 먼저 확인</span></li></ol><p>공식 메뉴에는 니기리 세트와 덮밥류가 있다고 안내되어 있지만, 덮밥의 이름·가격은 공개되어 있지 않아요. 4명이 나눠 먹어도 되는지 주문 전에 확인합니다.</p></div></div><h3>당일 보여주고 물어볼 문장</h3><div class="phrase-cards"><article><b>今日のおすすめのネタは何ですか？</b><span>쿄-노 오스스메노 네타와 난데스카?</span><p>오늘 추천하는 네타가 무엇인가요?</p></article><article><b>本日の海鮮丼、または旬の魚を使った丼はありますか？</b><span>혼지츠노 카이센동, 마타와 슌노 사카나오 츠캇타 돈와 아리마스카?</span><p>오늘의 해산물덮밥이나 제철 생선 덮밥이 있나요?</p></article><article><b>握りを二人前と、丼を二人前お願いします。取り分けてもよろしいですか？</b><span>니기리오 후타리마에토, 돈오 후타리마에 오네가이시마스. 토리와케테모 요로시이데스카?</span><p>니기리 2인분과 덮밥 2인분 주세요. 나눠 먹어도 될까요?</p></article></div><div class="guide-note"><b>덮밥이 없는 날</b><p>11관 니기리를 4인분 주문하면 총 ¥28,800입니다. 양이 많을 것 같으면 “シャリを少なめにできますか？”(샤리오 스쿠나메니 데키마스카? · 밥을 적게 해주실 수 있나요?)라고 물어봐요.</p></div>`,source('https://otaru-sushinakamura.com/menu.html','나카무라 공식 메뉴'))}
  function coffeeGuide(){return frame('coffee','스시 식후 B3 커피 30분',`<div class="guide-callout"><b>시간 기준</b><strong>14:05 도착 → 14:35 출발 → 15:00 오타루역</strong><p>주문 대기가 길면 테이크아웃으로 바꾸고, 14:40을 넘기지 않아요.</p></div><div class="guide-gallery two b3-menu">${photo(IMG.b3menu,'B3 COFFEE 음료 메뉴판','공개 메뉴 사진 · 현재 가격은 매장 메뉴판 우선')}${photo(IMG.b3food,'B3 COFFEE 푸드 메뉴판','공개 메뉴 사진 · 식후에는 디저트 1개만 나눠 먹기')}</div><div class="guide-cards compact-menu"><article><h4>1순위 · 카페라테</h4><b>カフェラテ · 공개 메뉴 ¥550</b><p>에스프레소와 우유의 균형이 좋아 부모님께 가장 무난해요.</p></article><article><h4>2순위 · 말차라테</h4><b>抹茶ラテ · 공개 메뉴 ¥600</b><p>커피를 원하지 않는 가족이 고르기 좋아요.</p></article><article><h4>함께 나눌 것 · 브라우니</h4><b>ダークチョコブラウニー · 공개 메뉴 ¥450</b><p>이미 스시를 먹었으니 1개만 주문해 네 명이 맛만 봐요.</p></article></div><div class="guide-note"><b>가격·영업시간 확인</b><p>메뉴 사진은 2023년 공개 자료라 현재 가격이 달라질 수 있어요. 토요일 영업과 최신 메뉴는 방문 직전 공식 인스타그램에서 다시 확인합니다.</p></div>`,source('https://www.instagram.com/b3.coffee.otaru/','B3 공식 인스타그램'))}
  function sapporoGiftGuide(){return frame('sapporo-gifts','다이마루·스텔라 65분 쇼핑',`<div class="guide-callout"><b>16:05~17:10</b><strong>다이마루 지하 1층 선물 먼저 → 스텔라 플레이스 필요한 매장만</strong><p>오타루에서 일반 르타오·롯카테이를 건너뛰었다면 이때 한 번에 구입해요.</p></div><h3>사진으로 고르는 삿포로 선물</h3><div class="guide-cards gift-cards"><article>${photo(IMG.harriet,'삿포로농학교 하리에트 3개입','공식 상품 사진 · 냉장 제품')}<h4>1순위 · 하리에트</h4><p>다이마루 삿포로점 한정. 폭신한 반죽에 커스터드와 생크림을 채운 디저트예요.</p><b>3개입 ¥972</b><span>지하 1층 · 10시/13시/16시 판매</span></article><article>${photo(IMG.yukipurin,'북과루 C-CUP 유키푸딩','사진: 다이마루 삿포로 공식 숍 블로그')}<h4>2순위 · C-CUP 유키푸딩</h4><p>다이마루점 한정. 치즈크림·시폰·우유푸딩을 섞어 먹는 냉장 디저트예요.</p><b>1개 ¥520</b><span>지하 1층 북과루</span></article><article><div class="text-photo letao-card">LeTAO<br><em>DAIMARU LIMITED</em></div><h4>3순위 · 갈레나티</h4><p>르타오의 다이마루 삿포로점 한정 견과류 갈레트. 상온 선물은 이것이 가장 편해요.</p><b>5개입 ¥1,620</b><span>지하 1층 르타오</span></article></div><div class="skip-later"><b>오타루에서 못 샀다면 여기서</b><span>르타오 일반 두블 프로마주</span><span>롯카테이 마르세이 버터샌드</span><span>카마에이 포장 어묵</span><p>냉장 상품은 다음 날 비행 전까지 보관 방법을 직원에게 확인해요. 가격은 2026년 8월 현장 표시가 우선입니다.</p></div>`,source('https://www.daimaru.co.jp/sapporo/topics/gourmet-143340.html','다이마루 한정 상품 공식 안내'))}
  function parcoGuide(){return frame('parco','PARCO 가방 쇼핑 90분',`<div class="guide-callout"><b>17:30~19:00 · 본관 1층</b><strong>BAO BAO → POTR → 결제·면세</strong><p>원하는 색상·크기를 먼저 보여주고 재고를 확인해요. 두 매장이 같은 층이라 이동 시간이 거의 들지 않습니다.</p></div><div class="shop-sequence"><article><b>1</b><div><small>어머니 우선</small><h3>BAO BAO ISSEY MIYAKE</h3><p>희망 모델·색상 재고부터 확인 · 면세 대상</p></div></article><article><b>2</b><div><small>PORTER 가방</small><h3>POTR SAPPORO</h3><p>실착 후 수납·끈 길이 확인 · 면세 대상</p></div></article><article><b>3</b><div><small>15~20분 확보</small><h3>결제·면세 처리</h3><p>여권과 결제카드를 준비해요.</p></div></article></div><div class="guide-note"><b>시간이 15분 이상 남을 때만</b><p>같은 건물 B1층의 <b>grenier</b>에서 유럽·미국·일본 빈티지 의류를 구경할 수 있어요. 별도 이동이 없지만 BAO BAO와 POTR 구매가 끝난 뒤에만 봅니다.</p></div>`,source('https://sapporo.parco.jp/floor/','삿포로 PARCO 공식 층별 안내'))}
  function suageGuide(){return frame('suage','Suage4 이후 커피 선택',`<div class="guide-callout caution"><b>현재 기본 일정에서는 비추천</b><strong>11:00 Suage4 → 12:05 짐 찾기 → 12:18 공항행 JR</strong><p>BARISTART 본점은 삿포로역이 아니라 오도리의 미나미1조 니시4초메에 있어, 식후에 들르면 다시 삿포로역으로 돌아와야 합니다.</p></div><div class="option-plans"><article><span>기본안 · 가장 안전</span><h3>Suage4 식사 후 바로 삿포로역</h3><p>11:50까지 식사를 끝내고 짐을 찾아 12:18 열차를 타요. 커피는 역 또는 공항에서 테이크아웃합니다.</p><b>부모님 동행 시 추천</b></article><article><span>BARISTART 우선 교체안</span><h3>JR타워 전망실 대신 오전 방문</h3><p>10:00 BARISTART → 10:20 출발 → 10:35 Suage4 대기 → 11:00 식사 → 12:18 열차</p><b>대표 메뉴: BARISTART 라테 R ¥700</b></article></div><div class="guide-note"><b>추천 주문</b><p>北海道産ミルクのBARISTARTラテをテイクアウトでお願いします。(홋카이도산 미루쿠노 바리스타토 라테오 테이크아우토데 오네가이시마스.) · 홋카이도 우유 바리스타트 라테를 테이크아웃으로 부탁합니다.</p></div>`,source('https://www.baristartcoffee.com/shopinfo/1705/','BARISTART 본점 공식 안내'))}
  function airportTrainGuide(){return frame('airport-train','공항행 Kitaca 잔액 안내',`<div class="balance-grid"><article><small>공항행만 남았을 때</small><strong>최소 ¥1,230</strong><b>안심 잔액 ¥1,500</b><p>삿포로역 → 신치토세공항역 성인 편도 운임이에요.</p></article><article><small>29·30일 교통 전체</small><strong>권장 잔액 ¥3,500</strong><b>오타루 왕복 ¥1,600 + 공항 ¥1,230 + 여유 ¥670</b><p>지하철이나 작은 추가 이동에도 대응할 수 있어요.</p></article><article><small>새 Kitaca 1장</small><strong>구입 ¥2,000</strong><b>실사용 잔액 ¥1,500</b><p>보증금 ¥500이 포함돼요. 오타루 왕복까지 쓸 카드라면 구입 후 ¥2,000을 추가 충전해 잔액 ¥3,500으로 맞춰요.</p></article></div><div class="guide-steps"><span><b>1</b>12:05까지 코인로커에서 짐 찾기</span><span><b>2</b>각 카드 잔액이 ¥1,500 이상인지 확인</span><span><b>3</b>12:18 전후 공항행 열차·승강장 확인</span><span><b>4</b>신치토세공항 지하역에서 하차</span></div>`,source('https://www.jrhokkaido.co.jp/airport/index.html','JR 홋카이도 공항선 공식 안내'))}
  function draw(kind){if(map){map.remove();map=null}if(!routes[kind]||!window.L)return;const p=routes[kind].points,pts=p.map(x=>[x[1],x[2]]);map=L.map('selected-guide-map',{scrollWheelZoom:false,zoomControl:false});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);L.polyline(pts,{color:kind==='dessert'?'#bc6b3d':'#196fa8',weight:5}).addTo(map);p.forEach((x,i)=>L.marker([x[1],x[2]],{icon:L.divIcon({className:`detail-marker ${kind}`,html:`<b>${i+1}</b>`,iconSize:[28,28],iconAnchor:[14,14]})}).addTo(map).bindPopup(`<strong>${esc(x[0])}</strong><br>${esc(x[3])}`));map.fitBounds(pts,{padding:[28,28]})}
  function mount(){const day=document.querySelector('.day-tabs button.active strong')?.textContent,active=document.querySelector('.item.active .item-content strong')?.textContent||'',overview=document.querySelector('.route-overview'),head=document.querySelector('.journey-head');let key='none',html='';if(day==='28일')[key,html]=dayOneGuide(active);if(day==='29일'){if(active==='JR로 오타루 이동'||active==='오타루에서 삿포로로 JR 이동'){key='train:'+active;html=trainGuide(active)}else if(active==='오타루운하 산책'){key='canal';html=mapGuide('canal')}else if(active==='사카이마치 디저트 산책'){key='dessert';html=mapGuide('dessert')}else if(active.includes('스시 나카무라')){key='nakamura';html=sushiGuide()}else if(active==='B3 COFFEE OTARU 식후 커피'){key='coffee';html=coffeeGuide()}else if(active==='다이마루·스텔라 플레이스 쇼핑'){key='sapporo-gifts';html=sapporoGiftGuide()}else if(active==='삿포로 PARCO 가방 쇼핑'){key='parco';html=parcoGuide()}}if(day==='30일'){if(active.includes('Suage4')){key='suage';html=suageGuide()}else if(active==='신치토세공항으로 이동'){key='airport-train';html=airportTrainGuide()}}if(key===lastKey&&document.querySelector('.detail-route'))return;lastKey=key;document.querySelector('.detail-route')?.remove();if(map){map.remove();map=null}if(key==='none'||!overview||!head)return;head.insertAdjacentHTML('beforebegin',html);if(routes[key])requestAnimationFrame(()=>draw(key))}
  new MutationObserver(()=>requestAnimationFrame(mount)).observe(document.documentElement,{childList:true,subtree:true});
})();
