const TOOL_DAYS=[
  {date:'2026-08-28',label:'28일 · 공항→비에이→삿포로',spots:[['신치토세',42.7752,141.6923],['비에이',43.5891,142.4630],['삿포로',43.0618,141.3545]]},
  {date:'2026-08-29',label:'29일 · 삿포로→오타루',spots:[['삿포로',43.0618,141.3545],['오타루',43.1907,140.9947]]},
  {date:'2026-08-30',label:'30일 · 삿포로→신치토세',spots:[['삿포로',43.0618,141.3545],['신치토세',42.7752,141.6923]]}
];
const WEATHER_TEXT={0:['☀️','맑음'],1:['🌤️','대체로 맑음'],2:['⛅','구름 조금'],3:['☁️','흐림'],45:['🌫️','안개'],48:['🌫️','서리 안개'],51:['🌦️','약한 이슬비'],53:['🌦️','이슬비'],55:['🌧️','강한 이슬비'],61:['🌦️','약한 비'],63:['🌧️','비'],65:['🌧️','강한 비'],71:['🌨️','약한 눈'],73:['🌨️','눈'],75:['❄️','강한 눈'],80:['🌦️','소나기'],81:['🌧️','소나기'],82:['⛈️','강한 소나기'],95:['⛈️','뇌우']};
const PHRASES=[['음식점 · 예약했어요','予約しています','요야쿠 시테이마스'],['음식점 · 이것으로 주세요','これをください','코레오 쿠다사이'],['음식점 · 계산 부탁합니다','お会計をお願いします','오카이케이오 오네가이시마스'],['택시 · 여기로 갈 수 있을까요?','ここまで行けますか','코코마데 이케마스카'],['택시 · 얼마나 걸릴까요?','どのくらいかかりますか','도노쿠라이 카카리마스카'],['택시 · 여기서 내려 주세요','ここで降ろしてください','코코데 오로시테 쿠다사이'],['상점 · 이것 있나요?','これはありますか','코레와 아리마스카'],['상점 · 카드 돼요?','カードは使えますか','카-도와 츠카에마스카'],['상점 · 면세되나요?','免税できますか','멘제이 데키마스카'],['길 · 화장실은 어디예요?','トイレはどこですか','토이레와 도코데스카'],['길 · ○○역은 어느 쪽인가요?','○○駅はどちらですか','○○에키와 도치라데스카'],['도움 · 천천히 말해 주세요','ゆっくり話してください','윳쿠리 하나시테 쿠다사이']];
const WORDS=[['메뉴','メニュー','메뉴-'],['계산','会計','카이케이'],['영수증','レシート','레시-토'],['정식 영수증','領収書','료-슈-쇼'],['할인','割引','와리비키'],['세금 포함','税込','제이코미'],['현금','現金','겐킨'],['엔','円','엔']];
function weatherCard(day){return `<article class="weather-day" data-weather-date="${day.date}"><header><strong>${day.label}</strong><small>지역별 예보</small></header><div class="weather-spots">${day.spots.map(s=>`<span><b>${s[0]}</b><i>예보 준비 중</i></span>`).join('')}</div></article>`}
function toolsMarkup(){return `<section id="travel-tools" class="travel-tools shell"><header class="tools-head"><p class="eyebrow dark">FAMILY TRAVEL TOOLS</p><h2>가족 여행 도구</h2><p>날씨와 환율, 꼭 필요한 일본어만 간단히 모았어요.</p></header><div class="tool-tabs" role="tablist"><button class="active" data-tool="weather">지역별 날씨</button><button data-tool="japanese">간단 일본어</button><button data-tool="exchange">엔화 계산</button></div><div class="tool-panel active" data-panel="weather"><div class="weather-note"><strong>☔ 이동 거리가 긴 날은 지역별로 확인해요.</strong><span>정확한 일기예보는 여행 16일 전부터 자동 표시됩니다.</span></div><div class="weather-grid">${TOOL_DAYS.map(weatherCard).join('')}</div><small class="tool-source">날씨: Open-Meteo · 출발 직전 일본 기상청과 함께 확인해 주세요.</small></div><div class="tool-panel" data-panel="japanese"><div class="phrase-grid">${PHRASES.map(x=>`<article><small>${x[0]}</small><strong lang="ja">${x[1]}</strong><span>${x[2]}</span></article>`).join('')}</div><h3>메뉴판에서 자주 보는 말</h3><div class="word-grid">${WORDS.map(x=>`<span><small>${x[0]}</small><b lang="ja">${x[1]}</b><i>${x[2]}</i></span>`).join('')}</div><details class="number-guide"><summary>숫자 1–10 보기</summary><p>1 一(이치) · 2 二(니) · 3 三(산) · 4 四(욘) · 5 五(고) · 6 六(로쿠) · 7 七(나나) · 8 八(하치) · 9 九(큐-) · 10 十(쥬-)</p></details></div><div class="tool-panel" data-panel="exchange"><div class="fx-card"><div><small id="fx-date">기준환율 불러오는 중</small><strong id="fx-rate">100엔 = —원</strong><span>카드사 수수료·환전 우대에 따라 실제 금액은 달라요.</span></div><div class="fx-calc"><label>엔화 금액<input id="yen-input" inputmode="numeric" type="number" min="0" step="100" value="1000"></label><b>≈</b><output id="won-output">—원</output></div></div><div class="money-tips"><article><b>💳 카드 결제</b><p>원화(KRW) 대신 <strong>엔화(JPY)</strong> 결제를 선택해요.</p></article><article><b>💴 현금 준비</b><p>알파카 먹이, 작은 매점과 자판기용으로 천엔권과 동전을 준비해요.</p></article><article><b>🧾 영수증</b><p>일반 영수증은 ‘레시-토’, 정식 영수증은 ‘료-슈-쇼’예요.</p></article></div><small class="tool-source">환율: Frankfurter 기준환율 · 결제 예상용</small></div></section>`}
async function loadWeather(){const days=Math.ceil((new Date('2026-08-28T12:00:00+09:00')-new Date())/86400000);if(days>16)return;for(const day of TOOL_DAYS){const card=document.querySelector(`[data-weather-date="${day.date}"]`);if(!card)continue;const spots=card.querySelectorAll('.weather-spots span');await Promise.all(day.spots.map(async(s,i)=>{try{const u=`https://api.open-meteo.com/v1/forecast?latitude=${s[1]}&longitude=${s[2]}&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=Asia%2FTokyo&start_date=${day.date}&end_date=${day.date}`;const j=await fetch(u).then(r=>r.json()),d=j.daily;if(!d?.time?.length)return;const w=WEATHER_TEXT[d.weather_code[0]]||['🌡️','날씨'];spots[i].querySelector('i').textContent=`${w[0]} ${d.temperature_2m_min[0]}–${d.temperature_2m_max[0]}° · 비 ${d.precipitation_probability_max[0]??'-'}%`}catch(e){spots[i].querySelector('i').textContent='출발 전 확인'}}))}}
async function loadRate(){let rate=9.3,date='';try{const j=await fetch('https://api.frankfurter.dev/v2/rate/JPY/KRW').then(r=>r.json());rate=Number(j.rate);date=j.date}catch(e){}const input=document.querySelector('#yen-input'),out=document.querySelector('#won-output');if(!input)return;document.querySelector('#fx-rate').textContent=`100엔 = ${Math.round(rate*100).toLocaleString('ko-KR')}원`;document.querySelector('#fx-date').textContent=date?`${date} 기준환율`:'간편 계산 기준';const calc=()=>out.textContent=`${Math.round(Number(input.value||0)*rate).toLocaleString('ko-KR')}원`;input.oninput=calc;calc()}
function mountTools(){const footer=document.querySelector('.trip-footer');if(!footer||document.querySelector('#travel-tools'))return;footer.insertAdjacentHTML('beforebegin',toolsMarkup());const nav=document.querySelector('.trip-nav div');if(nav&&!nav.querySelector('[href="#travel-tools"]'))nav.querySelector('[href="admin.html"]')?.insertAdjacentHTML('beforebegin','<a href="#travel-tools">여행 도구</a>');document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-panel]').forEach(x=>x.classList.toggle('active',x.dataset.panel===b.dataset.tool))});const legend=document.querySelector('.route-legend');if(document.querySelector('.day-tabs .active strong')?.textContent==='28일'&&legend&&!legend.querySelector('.branch'))legend.insertAdjacentHTML('beforeend','<span class="branch"><b>R</b>닛폰렌터카 삿포로역 앞점 · 오빠 반납</span>');loadWeather();loadRate()}
new MutationObserver(()=>mountTools()).observe(document.documentElement,{childList:true,subtree:true});mountTools();
